apiVersion: v1
kind: Namespace
metadata:
  name: uv

---
apiVersion: v1
kind: Pod
metadata:
  namespace: uv
  labels:
    run: uvpod
  name: uvpod
spec:
  volumes:
   - name: uvvol
     emptyDir: {}

  containers:
   - image: nginx
     name: uvc1
     ports:  
        - containerPort: 80
     volumeMounts:
        - name: uvvol
          mountPath: /usr/share/nginx/html/ 
   
   - image: alpine
     name: uvc2
     volumeMounts:
        - name: uvvol
          mountPath: /covid
     command: ["/bin/sh","-c","while true ; do cal 2020  >> /covid/index.html; sleep 20; done"]
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: uv
  labels:
    run: uvpod
  name: uvpod
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31355
  selector:
    run: uvpod
  type: NodePort
