apiVersion: v1
kind: Pod
metadata:
  labels:
    run: uvpod
  name: uvpod
spec:
  containers:
   - command: ["/bin/sh","-c","ping  fb.com"]
     image: alpine
     name: uvc1

   - image: busybox
     name: uvc2
     command: ["/bin/sh","-c","sleep 1000000"]
  restartPolicy: Never
