apiVersion: apps/v1
kind: Deployment
metadata:
        namespace: uv
        name: uv
        labels:
              app: my-app
spec:  
        template:
           metadata:
              name: nginx
              labels:
                app: my-app
           spec: 
                volumes:
                 - name: uvvol
                   hostPath:
                       path: /etc/passwd
                       type: File
                containers:
                   - image: nginx
                     name: nginx
                     volumeMounts:
                        - name: uvvol
                          mountPath: /usr/share/nginx/html/index.html
                restartPolicy: Always
        selector:
           matchLabels:
                app: my-app
        replicas: 3

---
apiVersion: v1
kind: Service
metadata:
  namespace: uv
  labels:
    app: my-app
  name: uv
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31366
  selector:
    app: my-app
  type: NodePort
